name: opstack next

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize]
env:
    CI: true
jobs:
    avoid_redundancy:
        runs-on: ubuntu-22.04
        permissions:
            actions: write
        timeout-minutes: 2
        steps:
            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  all_but_latest: true
                  access_token: ${{ github.token }}
    install-cache:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Commit
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: '18.17.0'
            - name: Cache npm dependencies
              uses: actions/cache@v4
              id: cache-dependencies
              with:
                  path: node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - name: Cache Playwright binary
              id: cache-playwright-binary
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: playwright-binary-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      playwright-binary-
            - name: Install Dependencies
              if: steps.cache-dependencies.outputs.cache-hit != 'true'
              run: |
                  npm install
    lint-format:
        runs-on: ubuntu-latest
        needs: install-cache
        steps:
            - name: Checkout Commit
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: '18.17.0'
            - name: Restore npm dependencies
              uses: actions/cache@v4
              id: cache-dependencies
              with:
                  path: node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - name: Run lint
              run: |
                  npm run lint
    type-check:
        runs-on: ubuntu-latest
        needs: install-cache
        steps:
            - name: Checkout Commit
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: '18.17.0'
            - name: Restore npm dependencies
              uses: actions/cache@v4
              id: cache-dependencies
              with:
                  path: node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - name: Check types
              run: |
                  npm run type-check
    build:
        runs-on: ubuntu-latest
        needs: [lint-format, type-check]
        steps:
            - name: Checkout Commit
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: '18.17.0'
            - name: Restore npm dependencies
              uses: actions/cache@v4
              id: cache-dependencies
              with:
                  path: node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - name: Run build
              run: |
                  npm run build
    unit-tests:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout Commit
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: '18.17.0'
            - name: Restore npm dependencies
              uses: actions/cache@v4
              id: cache-dependencies
              with:
                  path: node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - name: Run Tests
              shell: bash
              run: npm run test:unit
    e2e-tests-chrome:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout Commit
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: '18.17.0'
            - name: Restore npm dependencies
              uses: actions/cache@v4
              id: cache-dependencies
              with:
                  path: node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - name: Restore Playwright binary
              id: cache-playwright-binary
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: playwright-binary-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      playwright-binary-
            - name: Install playwright
              run: npx playwright install --with-deps
            - name: Run Tests
              shell: bash
              run: npm run test:e2e
